GymPlanner/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls'))
]

app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('trainings/', views.trainings, name='trainings'),
    path('plans/', views.plans, name='plans'),
    path('exercises', views.exercises, name='exercise_list'),
    path('userexercises/', views.user_exercises, name='userexercise_list'),
    path('remove_userexercise_from_training/<int:training_id>/<int:userexercise_id>/',
         views.remove_userexercise_from_training, name='remove_userexercise_from_training'),
    path('create_exercise/<int:ex_id>/', views.CreateUserExercise.as_view(), name='create_userexercise'),
    path('update_exercise/<int:pk>/', views.UpdateUserExercise.as_view(), name='update_userexercise'),
    path('delete_exercise/<int:pk>/', views.DeleteUserExercise.as_view(), name='delete_userexercise'),
    path('exercises/<int:ex_id>/', views.exercise_detail, name='exercise_detail'),
    path('create_training/', views.CreateTraining.as_view(), name='create_training'),
    path('update_training/<int:pk>/', views.UpdateTraining.as_view(), name='update_training'),
    path('delete_training/<int:pk>/', views.DeleteTraining.as_view(), name='delete_training'),
    path('training_details/<int:training_id>', views.training_details, name='training_details'),
    path('plan_details/<int:plan_id>', views.plan_details, name='plan_details'),
    path('create_plan/', views.CreatePlan.as_view(), name='create_plan'),
    path('update_plan/<int:pk>/', views.UpdatePlan.as_view(), name='update_plan'),
    path('delete_plan/<int:pk>/', views.DeletePlan.as_view(), name='delete_plan'),
    path('remove_training_from_plan/<int:plan_id>/<int:training_id>', views.remove_training_from_plan,
         name='remove_training_from_plan')

]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    genders = [("M", "Male"), ("F", "Female")]
    birth_date = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=10, choices=genders, null=True, blank=True)

    def __str__(self):
        return self.user.email


class Exercise(models.Model):
    name = models.CharField(max_length=100)
    target_muscle = models.CharField(max_length=100)
    equipment = models.CharField(null=True, max_length=100)
    youtube_url = models.URLField(null=True, blank=True)

    def __str__(self):
        return self.name


class Plan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start_date = models.DateField()
    end_date = models.DateField(null=True, blank=True)
    name = models.CharField(max_length=50)
    goals = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f"{self.name} | {self.start_date}"


class Training(models.Model):
    trainingTypes = [('FBW', 'FBW'),
                     ('Push', 'Push'),
                     ('Pull', 'Pull'),
                     ('Upper', 'Upper'),
                     ('Lower', 'Lower'),
                     ('Custom', 'Custom')]
    days = [(1, 'Monday'),
            (2, 'Tuesday'),
            (3, 'Wednesday'),
            (4, 'Thursday'),
            (5, 'Friday'),
            (6, 'Saturday'),
            (7, 'Sunday')]
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, blank=True)
    plan = models.ForeignKey(Plan, on_delete=models.SET_NULL, null=True, blank=True)
    weekday = models.IntegerField(blank=True, choices=days)
    type = models.CharField(blank=True, max_length=10, choices=trainingTypes)

    def __str__(self):
        return self.name


class UserExercise(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    training = models.ForeignKey(Training, on_delete=models.SET_NULL, null=True, blank=True)
    exercise = models.ForeignKey(Exercise, on_delete=models.CASCADE)
    setsNumber = models.IntegerField()
    repsNumber = models.IntegerField()
    tempo = models.CharField(max_length=10, null=True, blank=True)
    weight = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=3)
    notes = models.TextField(max_length=255, blank=True, null=True)

    def __str__(self):
        return self.exercise.name


class ExerciseProgress(models.Model):
    user_exercise = models.ForeignKey(UserExercise, on_delete=models.CASCADE)
    date = models.DateField()
    actual_sets = models.IntegerField()
    actual_reps = models.IntegerField()
    actual_weight = models.DecimalField(blank=True, null=True, max_digits=5, decimal_places=3)

    def __str__(self):
        return f"ExerciseProgress: {self.user_exercise.exercise.name}, User: {self.user_exercise.user.email}, Date: {self.date}"

app/templates/app/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GymPlanner</title>
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'theme.css' %}">
    <link rel="stylesheet" href="{% static 'table_styling.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    <style>
        body {
            font-family: 'Poppins', sans-serif;
        }
        .navbar-brand {
            font-weight: 500;
        }
        .navbar-nav .nav-link {
            font-weight: 300;
        }
    </style>
</head>
<body>
{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    </div>
{% endif %}
<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="">GymPlanner</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" href="{% url 'app:home' %}">Homepage</a>
                <a class="nav-link" href="{% url 'app:exercise_list' %}">Exercises</a>
                {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'app:userexercise_list' %}">Your exercises</a>
                    <a class="nav-link" href="{% url 'app:trainings' %}">Trainings</a>
                    <a class="nav-link" href="{% url 'app:plans' %}">Plans</a>
                    <a class="nav-link" href="{% url 'app:profile' %}">Profile</a>
                    <a class="nav-link" href="{% url 'app:logout' %}">Logout</a>
                {% endif %}
                {% if user.is_superuser %}
                    <a class="nav-link" href="/admin">Admin</a>
                {% endif %}
                {% if not user.is_authenticated %}
                    <a class="nav-link" href="{% url 'app:login' %}">Sign in</a>
                {% endif %}
            </div>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

app/templates/app/exercise_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Exercise Detail</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    <h1>Exercise Details</h1>
    <table>
        <tr>
            <th>Name</th>
            <td>{{ exercise.name }}</td>
        </tr>
        <tr>
            <th>Target Muscle</th>
            <td>{{ exercise.target_muscle }}</td>
        </tr>
        <tr>
            <th>Equipment</th>
            <td>{{ exercise.equipment }}</td>
        </tr>
    </table>
    {% if exercise.youtube_url %}
        <h2>Exercise Video</h2>
        <iframe
                src="https://www.youtube.com/embed/{{ exercise.youtube_url|cut:'https://www.youtube.com/watch?v=' }}"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen
                width="1280"
                height="720">
        </iframe>
    {% endif %}
{% endblock content %}

</body>
</html>

app/templates/app/exercise_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Exercises</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    {% if exercises %}
        <ul>
            {% for ex in exercises %}
                <li>
                    <a href="{% url 'app:exercise_detail' ex.id %}">{{ ex.name }}</a>
                    {% if user.is_authenticated %}
{#                        <a href="{% url 'app:create_userexercise' ex.id %}">Create your#}
{#                            variant </a>#}
                        <button type="button"  onclick="location.href='{% url 'app:create_userexercise' ex.id %}'">Create your variant</button>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No exercises are available.</p>
    {% endif %}
{% endblock content %}

</body>
</html>

app/templates/app/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
{% extends 'app/base.html' %}

{% block content %}
    {% if not user.is_authenticated %}
        <h1>Welcome to GymPlanner</h1>
        <p>
            To create your personal plans you have to sign up.
        </p>
        <p>
            If you already have account just sign in.
        </p>
        <p>
            <a href="{% url 'app:login' %}">Sign up/Sign in</a>
        </p>
    {% else %}
        Hello {{ user.email }}!
    {% endif %}

{% endblock content %}

</body>
</html>

app/templates/app/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login</title>
</head>
<body>
{% load socialaccount %}
<h2>Login</h2>
<form method="post" action="{% url 'account_login' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>
<p>
    <a href="{% url 'account_signup' %}">Sign up</a>
</p>
<p>
    <a href="{% provider_login_url 'google' %}?next={% url 'app:home' %}">Login with Google</a>
</p>

</body>
</html>

app/templates/app/plan_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}
</body>
</html>

app/templates/app/plan_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Plan details</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    <h2>{{ plan.name }}</h2>
    {% if trainings %}
        <table>
            <thead>
            <tr>
                <th>Training</th>
                <th>Type</th>
                <th>Weekday</th>
            </tr>
            </thead>
            <tbody>
            {% for training in trainings %}
                <tr>
                    <td>{{ training.name }}</td>
                    <td>{{ training.type }}</td>
                    <td>{{ training.get_weekday_display }}</td>
                    <td>
                        <a href="{% url 'app:training_details' training.id %}">Details</a>
                    </td>
                    <td>
                        <a class="delete"
                           href="{% url 'app:remove_training_from_plan' plan.id training.id %}">Remove</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You haven't added any trainings to the plan yet.</p>
    {% endif %}
    <a href="{% url 'app:trainings' %}">Add training</a>
{% endblock content %}
</body>
</html>

app/templates/app/plan_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create Plan</title>
</head>
<body>
{% extends "app/base.html" %}

{% block content %}
    <h2>{{ plan.name }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}
</body>
</html>

app/templates/app/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Profile</title>
</head>
<body>
    {% extends 'app/base.html' %}
    {% block content %}
    <h2>Profile</h2>
    <p>Welcome, {{ user.email }}</p>
    <a href="{% url 'account_logout' %}">Logout</a>
    {% endblock content %}
</body>
</html>

app/templates/app/training_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}
</body>
</html>

app/templates/app/training_details.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
{% if user_exercises %}
    <table>
        <thead>
            <tr>
                <th>Exercise</th>
                <th>Sets Number</th>
                <th>Reps Number</th>
                <th>Tempo</th>
                <th>Weight</th>
                <th>Notes</th>
            </tr>
        </thead>
        <tbody>
            {% for user_exercise in user_exercises %}
                <tr>
                    <td>{{ user_exercise.exercise.name }}</td>
                    <td>{{ user_exercise.setsNumber }}</td>
                    <td>{{ user_exercise.repsNumber }}</td>
                    <td>{{ user_exercise.tempo }}</td>
                    <td>{{ user_exercise.weight }}</td>
                    <td>{{ user_exercise.notes }}</td>
                    <td><a href="{% url 'app:update_userexercise' user_exercise.id %}">Edit</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p>You haven't added any exercises to the training yet.</p>
{% endif %}
{% endblock content %}
</body>
</html>

app/templates/app/training_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create training</title>
</head>
<body>
{% extends "app/base.html" %}

{% block content %}
    <h2>{{ training.name }}</h2>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}
</body>
</html>

app/templates/app/userexercise_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete</title>
</head>
<body>
{% extends 'app/base.html' %}
{% block content %}
    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        {{ form }}
        <input type="submit" value="Confirm">
    </form>
{% endblock content %}
</body>
</html>

app/templates/app/userexercise_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create your exercise</title>
</head>
<body>
{% extends "app/base.html" %}

{% block content %}
    <form action="" method="post">
        <h2>{{ exercise.name }}</h2>
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit"/>
    </form>
{% endblock %}
</body>
</html>